name: Test artifact uploading

on:
  push:
    branches: [ master ]

jobs:
  mitmproxy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: KOLANICH-GHActions/mitmproxy@master
